### ISSUE TITLE
Support Ruby 3.1

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-nist#151]
* [ ] Update GitHub Actions to also run Ruby 3.1
* [ ] The Ruby Regexp lines in the YAML fails to run in Ruby 3.1 due to the Psych parser at version >= 4.0.

Ref: https://github.com/ytti/oxidized/issues/2305

**Comment by mico** [comment]
Adding dependency for psych 3.3.2 fixed issue "Tried to load unspecified class: Regexp".
