### ISSUE TITLE
Final PubID scheme: Part number should be `[A-Z0-9]`

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-nist#154]
From #28 

Should the Part number, if in alphabet, be capitalised?

* “NIST SP 800-131a” => “NIST SP 800-131A”? (The base document “NIST SP 800-131a” has a R1 as “NIST SP 800-131Ar1”.)
* "NIST SP 800-38a” => "NIST SP 800-38A”? ("NIST SP 800-38a” but "NIST SP 800-38F”)

Answer is YES.
<img width="771" alt="Screenshot 2022-04-07 at 2 15 32 PM" src="https://user-images.githubusercontent.com/11865/162132478-ddb61f3e-f8e3-4489-ac8d-a98fd5031118.png">

**Comment by ronaldtse** [comment]
This is already implemented in #86 . @mico can you confirm that there is nothing further to do?

**Comment by mico** [comment]
https://github.com/metanorma/pubid-nist/blob/3014890b5483c2111f74e57b71f2e7e326f208fb/lib/pubid/nist/document_transform.rb#L9-L10
@ronaldtse Part number always up cased
