### ISSUE TITLE
This gem depends on relaton-nist

### ISSUE THREAD

**Issue by andrew2net** [metanorma/pubid-nist#158]
This gem is supposed to be used in the relaton-nist isn't it? But it depends on the relaton-nist,
https://github.com/metanorma/pubid-nist/blob/98dfdb37498ed6ec8beed82d7355d8e0988d0fa7/pubid-nist.gemspec#L32
 so it's impossible to include this gem to relaton-nist dependency
```
bundle update
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Your bundle requires gems that depend on each other, creating an infinite loop. Please remove either gem 'pubid-nist' or gem 'relaton-nist' and try again.
```
Can we remove the `relaton-nist` dependency from this gem?

**Comment by ronaldtse** [comment]
Yes we must remove Relaton-NIST as a dependency. There is no reason to include it here.
