### ISSUE TITLE
Parsing: abbreviation "Ver." not recognised

### ISSUE THREAD

**Issue by andrew2net** [metanorma/pubid-nist#160]
In the NIST source dataset, there are documents with identifiers like `NIST SP 800-63 Ver. 1.0`. The pubid-nist gem should this kind of version abbreviation.
```ruby
> Pubid::Nist::Document.parse("NIST SP 800-63 Ver. 1.0")
Failed to match sequence (STAGE? (' ' / '.') REPORT_NUMBER parts:(PARTS{0, })) at line 1 char 8.
cause: Failed to match sequence (STAGE? (' ' / '.') REPORT_NUMBER parts:(PARTS{0, })) at line 1 char 8.
...
```

**Comment by ronaldtse** [comment]
@andrew2net can you provide a few more of these identifiers? Where did you get them from? Thanks.

@mico this is only for parsing -- when we generate we must follow PubID.

**Comment by andrew2net** [comment]
@ronaldtse I get the identifiers from https://csrc.nist.gov/CSRC/media/feeds/metanorma/pubs-export.zip
```
SP 800-60 Ver. 2.0
SP 800-63 Ver. 1.0
SP 800-63 Ver. 1.0.1
SP 800-63 Ver. 1.0.2
SP 800-67 Ver. 1
```
Not so much but we need to handle then somehow.

**Comment by ronaldtse** [comment]
@andrew2net yes we must handle these identifiers because they are directly from NIST CSRC. Thanks.
