### ISSUE TITLE
Parsing drafts

### ISSUE THREAD

**Issue by andrew2net** [metanorma/pubid-nist#164]
@mico how should drafts be encoded into identifiers? I've tried `NIST SP 2PD 1800-13B` and got an error:
```
Pubid::Nist::Document.parse("NIST SP 1PD 800-189")
Failed to match sequence (STAGE? (' ' / '.') REPORT_NUMBER parts:(PARTS{0, })) at line 1 char 3.
cause: Failed to match sequence (STAGE? (' ' / '.') REPORT_NUMBER parts:(PARTS{0, })) at line 1 char 3.
`- Extra input after last repetition at line 1 char 3.
   `- Expected one of [EDITION, REVISION, VERSION, VOLUME, PART, UPDATE, ADDENDUM, TRANSLATION, SUPPLEMENT, ERRATA, INDEX, INSERT, SECTION, APPENDIX] at line 1 char 3.
...
```
In the data source there are also identifiers like `SP 800-189 (Draft)` and `NIST.SP.800-189-draft2` that the pubid-nist fails to parse too.

**Comment by ronaldtse** [comment]
These seem like bugs. @andrew2net can you help separate the bugs into different issues? Thanks!

**Comment by andrew2net** [comment]
@mico we still need to parse the drafts stages. We also use the drafts stages in references and need to parse them.
https://github.com/relaton/relaton-nist#get-short-citation

**Comment by ronaldtse** [comment]
Yes we need to handle this.

**Comment by mico** [comment]
> @mico how should drafts be encoded into identifiers? I've tried `NIST SP 2PD 1800-13B` and got an error:

Draft stage should be inside brackets, like `NIST SP(2PD) 1800-13B` then parser will be able to process it.
Here you can find available stages: https://github.com/metanorma/pubid-nist/blob/main/stages.yaml

We don't have "1PD" stage, but we have "IPD".
@ronaldtse do we need to add "1PD"?

**Comment by ronaldtse** [comment]
> We don't have "1PD" stage, but we have "IPD".

"IPD" (initial public draft) is the official stage for "1PD". We should support parsing "1PD" and rendering it as "IPD".

> Draft stage should be inside brackets, like NIST SP(2PD) 1800-13B then parser will be able to process it.

From PubID 1.0:
<img width="579" alt="Screenshot 2023-04-17 at 12 50 33 PM" src="https://user-images.githubusercontent.com/11865/232381167-01440f3b-276a-434f-a0e3-49a7825e4fc6.png">

The stage is now rendered outside brackets and after the doc number, but before the language code.

<img width="721" alt="Screenshot 2023-04-17 at 12 52 03 PM" src="https://user-images.githubusercontent.com/11865/232381395-ec86425b-64d3-4ae9-9169-0293150b5dd6.png">

@mico we need to update the PubID output (2.3 of PubID 1.0):
<img width="981" alt="Screenshot 2023-04-17 at 12 53 17 PM" src="https://user-images.githubusercontent.com/11865/232381739-3a5af3a6-e28c-4967-9bc6-14d7bc53a519.png">

**Comment by mico** [comment]
related #153

**Comment by mico** [comment]
> @mico how should drafts be encoded into identifiers? I've tried `NIST SP 2PD 1800-13B` and got an error:
> Pubid::Nist::Document.parse("NIST SP 1PD 800-189")
> In the data source there are also identifiers like `SP 800-189 (Draft)` and `NIST.SP.800-189-draft2` that the pubid-nist fails to parse too.

@ronaldtse Do we need to parse exactly `NIST SP 2PD 1800-13B`? Old identifiers would have something like `NIST SP(2PD) 1800-13B`. I didn't manage to find this identifier online.
The same question about `NIST SP 1PD 800-189`.
Do we need to parse `SP 800-189 (Draft)` and `NIST.SP.800-189-draft2`? Do we have other examples like that?

**Comment by ronaldtse** [comment]
@mico For drafts, the only dataset that contains them is the NIST Metanorma bibliographic dataset. We only need to parse the identifiers that are currently in this dataset:
* https://csrc.nist.gov/CSRC/media/feeds/metanorma/pubs-export.json

**Comment by mico** [comment]
> @mico For drafts, the only dataset that contains them is the NIST Metanorma bibliographic dataset. We only need to parse the identifiers that are currently in this dataset:
> 
> * https://csrc.nist.gov/CSRC/media/feeds/metanorma/pubs-export.json
> 
> The "draft" documents in this dataset are what I call "old identifier format", so we just need to support these.

@ronaldtse what the output should be for "draft" document?

For some documents, I can see it's "pd":
```
    "docidentifier": "SP 1800-19 (Draft)",
    "title-sub": "Security Practice Guide for VMware Hybrid Cloud Infrastructure as a Service (IaaS) Environments (Preliminary Draft)",
```

For for some there are no information other than just a "draft": `SP 1800-1 (Draft)`

**Comment by ronaldtse** [comment]
For "Draft" I think we can consider that "Pubic Draft", i.e. IPD.

**Comment by mico** [comment]
> For "Draft" I think we can consider that "Pubic Draft", i.e. IPD.

It will be not correct for `SP 1800-19 (Draft)`, it's "prd" (Preliminary Draft), I made a mistake in previous message.

**Comment by ronaldtse** [comment]
Ah okay.
