### ISSUE TITLE
Identifiers with minor version

### ISSUE THREAD

**Issue by andrew2net** [metanorma/pubid-nist#165]
There are identifiers like `"NIST SP 800-63ver1.0.2"`, with minor and bugfix numbers of version. We should be able to parse that kind of version.

**Comment by ronaldtse** [comment]
Agree.

**Comment by mico** [comment]
> There are identifiers like `"NIST SP 800-63ver1.0.2"`, with minor and bugfix numbers of version. We should be able to parse that kind of version.

I just checked, it's parsing successfully.
We even have a test for that one:
https://github.com/metanorma/pubid-nist/blob/80efab99f38a295e1120547d44438677b9e1cd5b/spec/nist_pubid/document/nist_sp_spec.rb#L191-L196
