### ISSUE TITLE
Auto-release issue: GHA jobs no longer being executed possibly due to ubuntu-18 requirement

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-nist#170]
This issue was reported by @mico.

The auto-release job no longer works, the job just queues and never gets run:
* https://github.com/metanorma/pubid-nist/actions/runs/4717413839

The messages are:
```
Requested labels: ubuntu-18.04
Job defined at: metanorma/pubid-nist/.github/workflows/release.yml@refs/tags/v0.2.1
Waiting for a runner to pick up this job...
```

This is likely because ubuntu-18.04 runners have been removed from GHA.

Moreover, we probably have other gems that use such workflow but are not longer working.

@CAMOBAP can you please help update all these GHA workflows to use working runners (no longer ubuntu-18.04)? Thanks!

**Comment by CAMOBAP** [comment]
@ronaldtse CI is updated

Also, I see that [v0.2.1](https://github.com/metanorma/pubid-nist/tree/v0.2.1) tag was pushed but `gemspec` file wasn't updated properly, so I retagged it and pushed again

UPD. Issue found in common release workflow, investigating it

**Comment by CAMOBAP** [comment]
Fixed and released
