### ISSUE TITLE
"FIPS" documents should not have "NIST" prefix

### ISSUE THREAD

**Issue by andrew2net** [metanorma/pubid-nist#195]
When parsing "NIST FIPS 140-2" and rendering it we get "NIST FIPS PUB 140-2"
```ruby
> Pubid::Nist::Identifier.parse("NIST FIPS 140-2").to_s
"NIST FIPS PUB 140-2"
```
There aren't "NIST FIPS PUB NNN" documents in the source datasets that we use. There are only "NIST FIPS NNN"

**Comment by ronaldtse** [comment]
@mico this is a bug to be fixed, thanks. The "FIPS" documents do not have the "NIST" prefix.

**Comment by mico** [comment]
> @mico this is a bug to be fixed, thanks. The "FIPS" documents do not have the "NIST" prefix.

@ronaldtse Andrei's point was about "FIPS PUB" vs "FIPS". Source datasets don't have a "PUB" part. @andrew2net is it correct?

**Comment by andrew2net** [comment]
@mico yes, the question was about "FIPS PUB" vs "FIPS". However, I was wrong adding NIST prefix to all the IDs.
The pubs-export dataset has FIPS and SP series. SP series should be prefixed with NIST but FISP shouldn't. So we have two issues now:
- The pubid-nist should parse "FIPS NNN-N".
- FIPS series should be rendered without PUB.

@ronaldtse I don't know if "FIPS PUB" sereis exists. Can you confirm if it exists or no?

**Comment by mico** [comment]
> @ronaldtse I don't know if "FIPS PUB" sereis exists. Can you confirm if it exists or no?

https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.140-2.pdf
Everywhere in the document it appears as `FIPS PUB 140-2`

**Comment by andrew2net** [comment]
@mico I see that the PDF documents have "FISP PUB" series. But the IDs in the data source and on the site are without "PUB".
https://csrc.nist.gov/pubs/fips/140-2/upd1/final
https://csrc.nist.gov/pubs/fips/140-2/final
https://csrc.nist.gov/pubs/fips/140-2/final

Now this gem can parse "FIPS 140-2" without "NIST" prefix. It's good. However, it still render pbid with "NIST" prefix.
```ruby
> pry(main)> Pubid::Nist::Identifier.parse('FIPS 140-2').to_s
=> "NIST FIPS 140-2"
```

**Comment by mico** [comment]
> However, it still render pbid with "NIST" prefix

@andrew2net According to standard https://www.nist.gov/system/files/documents/2022/04/01/PubID_Syntax_NIST_TechPubs.pdf we should render "FIPS" prefixed with "NIST". I already mentioned this above.

**Comment by andrew2net** [comment]
@mico I missed it, sorry.

**Comment by ronaldtse** [comment]
Thank you @mico @andrew2net , I agree with the current implementation as per PubID 1.0.
