### ISSUE TITLE
URGENT parse all IDs from pubs-export

### ISSUE THREAD

**Issue by andrew2net** [metanorma/pubid-nist#196]
NIST updated the pubs-export dataset. We need to parse all the IDs from the dataset.
[pubs-export.txt](https://github.com/metanorma/pubid-nist/files/12566979/pubs-export.txt)

**Comment by ronaldtse** [comment]
Can we have a rake task that can help us fetch the latest set of PubIDs to test the parser against? Thanks.

**Comment by mico** [comment]
> NIST updated the pubs-export dataset. We need to parse all the IDs from the dataset.
> [pubs-export.txt](https://github.com/metanorma/pubid-nist/files/12566979/pubs-export.txt)

@andrew2net How can I fetch the latest version of this file?
