### ISSUE TITLE
URGENT Parsing addendums

### ISSUE THREAD

**Issue by andrew2net** [metanorma/pubid-nist#203]
We need to parse addendums in any format and get an equivalent result. For example if we parse "NIST SP 800-38A Add. 1" and "NIST.SP.800-38A.add-1" the addedndums should be equivalent, i.e. `id1.addedndum == id2.addendum` should be true.
Currently we have:
```ruby
# Addendem fails to parse
> Pubid::Nist::Identifier.parse "NIST SP 800-38A Add. 1"
Failed to match sequence (OLD_STAGE? (' ' / '.') REPORT_NUMBER PARTS{0, } DRAFT? STAGE? TRANSLATION?) at line 1 char 9.
cause: Failed to match sequence (OLD_STAGE? (' ' / '.') REPORT_NUMBER PARTS{0, } DRAFT? STAGE? TRANSLATION?) at line 1 char 9.
`- Don't know what to do with ". 1" at line 1 char 13.

# The only addedndum I foud that is parsed
> id1 = Pubid::Nist::Identifier.parse "NIST SP 800-38a-add"
#<Pubid::Nist::Identifier:0x000000010a483d60 @publisher=#<Pubid::Nist::Publisher:0x000000010b26c9b8 @publisher="NIST">, @serie=#<Pubid::Nist::Serie:0x000000010b26cc88 @serie="NIST SP", @parsed=nil>, @code="800-38A", @supplement=nil, @update=nil, @addendum="-add">

> id1.addendum
"-add"

# MR addedum with number is parsed without error
> id2 = Pubid::Nist::Identifier.parse "NIST.SP.800-38A.add-1"
#<Pubid::Nist::Identifier:0x000000010a46a298 @publisher=#<Pubid::Nist::Publisher:0x000000010b58ee98 @publisher="NIST">, @serie=#<Pubid::Nist::Serie:0x000000010b58f140 @serie="NIST SP", @parsed=nil>, @code="800-38A", @supplement=nil, @update=nil, @addendum=".add-1">

> id2.addendum
".add-1"

# MR addendum without number is recognized as `translation`
> Pubid::Nist::Identifier.parse "NIST.SP.800-38A.add"
#<Pubid::Nist::Identifier:0x000000010a4812e0 @publisher=#<Pubid::Nist::Publisher:0x000000010b563888 @publisher="NIST">, @serie=#<Pubid::Nist::Serie:0x000000010b563b30 @serie="NIST SP", @parsed=nil>, @code="800-38A", @supplement=nil, @update=nil, @translation="add">
```
We need to parse addedndums with and without numbers. Here is an example of addendum witout number https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38a-add.pdf
I suugest that `id.addendum` should be a String and contains just number or empty string if an addendum has no number.

**Comment by mico** [comment]
@andrew2net the reason `NIST SP 800-38A Add. 1` not parsable because [NIST Tech Pubs](https://raw.githubusercontent.com/usnistgov/NIST-Tech-Pubs/nist-pages/xml/allrecords.xml) I was using for testing don't have identifier in this format.
Probably issue not only with addendum, we're already experiencing a similar issue with "update".
Maybe we should add tests to make sure we can parse output as well.
@ronaldtse what do you think?

**Comment by andrew2net** [comment]
@mico Ok. It ssems we don't have ammendments numbers in NIST, but it's not clear from the [doc](https://github.com/metanorma/pubid-nist#part). We need to describe somehow that, for example, the Part and Volume should be with numbers, and Addendum shouldn't.
What's a parsable format? This `NIST SP 800-38A-add`? But it's redered as `NIST SP 800-38A Add.` and the output is not parsable.
The pubid should be able to parse it's output with same result.
And all attributes should be comparable. I.e. `id1.addendum == id2.addendum` and `id1.revision == id2.revision`, even if `id1` and `id2` parsed from differnt ID formats (long, short, or MR).
