### ISSUE TITLE
Update series long description

### ISSUE THREAD

**Issue by mico** [metanorma/pubid-nist#222]
related #217 

Changes in series description here https://www.nist.gov/system/files/documents/2022/04/01/PubID_Syntax_NIST_TechPubs.pdf is not reflected in code base, for example:

AMS was "Advanced Manufacturing Standard" become "Advanced Manufacturing Series".
CSWP was "Cybersecurity Resource Center White Paper" become "Cybersecurity White Papers".

```
AMS Advanced Manufacturing Series
BH Building and Housing
BMS Building Materials and Structures Reports
BSS Building Science Series
CIRC NBS Circulars
CS Commercial Standards
CSM Commercial Standards Monthly
CSWP NIST Cybersecurity White Papers
EAB Economic Analysis Briefs
FIPS Federal Information Processing Standards Publications
GCR Grantee/Contractor Reports
HB Handbooks
IR NISTIR
MONO Monographs
MP Miscellaneous Publications
NCSTAR National Construction Safety Team Act Reports
NSRDS National Standard Reference Data Series
OWMWP Office of Weights and Measures White Papers
PC Photographic Laboratory Circulars
RPT National Bureau of Standards Reports
SIBS Special Interior Ballistic Studies
SP Special Publications
TIBM Technical Information on Building Materials for Use in the Design of Low Cost Housing
TN Technical Notes
TTB Technology Transfer Briefs
```

**Comment by mico** [comment]
> IR NISTIR

@ronaldtse this looks strange.

before it was:

```
  NIST IR: Interagency or Internal Report
  NBS IR: Interagency or Internal Report
```

**Comment by ronaldtse** [comment]
> > IR NISTIR
> 
> @ronaldtse this looks strange.
> 
> before it was:
> 
> ```
>   NIST IR: Interagency or Internal Report
>   NBS IR: Interagency or Internal Report
> ```

I believe the reason they did that is exactly to remove the “or”. We should just adopt whatever they specify here.

**Comment by mico** [comment]
> I believe the reason they did that is exactly to remove the “or”. We should just adopt whatever they specify here.

@ronaldtse I don't understand. "NISTIR" is an abbreviation, but abbreviation on the left side is "IR", right side should have decoded abbreviation. It looks like mistake, why we should have another abbreviation on right side?

**Comment by ronaldtse** [comment]
@mico the reason why they just used "NISTIR" as the long description for "NIST IR", is because there are 2 types of documents shared under this "NIST IR" document type. Some of them are:
* NIST Interagency Reports
* NIST Internal Reports

They cannot split this series because it was published since so many years ago. So that's why they gave up on the long name and just used "NISTIR" instead. In some sense this is like how "GNU" stands for "GNU is Not Unix" which doesn't really mean anything.
