### ISSUE TITLE
Raise an error when type for stage is not provided

### ISSUE THREAD

**Issue by mico** [metanorma/pubid-nist#224]
```
{:number=>"1000", :serie=>"FIPS", :edition_year=>"2001", 
:stage=> Pubid::Nist::Stage.new(id: "3", type: nil)}
````

* Short:
  * Before: NIST FIPS 1000 (February 01, 2000)
  * After: NIST FIPS 1000e2001 3

* Long:
   * Before: NIST Federal Information Processing Standards Publication 1000 (February 01, 2000)
   * After: National Institute of Standards and Technology Federal Information Processing Standards Publication 1000 (Third ) (2001)

**NOTE: I doubt "(Third )" is correct**

* Machine-Readable:
  * Before: NIST.FIPS.[-3].1000.eng
  * After:  NIST.FIPS.1000e2001.3

_Originally posted by @opoudjis in https://github.com/metanorma/metanorma-nist/issues/392#issuecomment-1878632118_

**Comment by mico** [comment]
@opoudjis I believe we shouldn't accept `type == nil`
As you can see parameter "type" is required and for 99% of cases that means I don't expect `nil` will be provided.

Maybe I should add verification and raise an error when `nil` received for parameter where we don't expect `nil`

**Comment by opoudjis** [comment]
Agreed. I will supply a default type.

**Comment by ronaldtse** [comment]
> I believe we shouldn't accept `type == nil` 

Can we throw an error for this?
