### ISSUE TITLE
Update long description for "IR" series to "NISTIR"

### ISSUE THREAD

**Issue by mico** [metanorma/pubid-nist#225]
@mico the reason why they just used "NISTIR" as the long description for "NIST IR", is because there are 2 types of documents shared under this "NIST IR" document type. Some of them are:
* NIST Interagency Reports
* NIST Internal Reports

They cannot split this series because it was published since so many years ago. So that's why they gave up on the long name and just used "NISTIR" instead. In some sense this is like how "GNU" stands for "GNU is Not Unix" which doesn't really mean anything.

_Originally posted by @ronaldtse in https://github.com/metanorma/pubid-nist/issues/222#issuecomment-1956306016_

**Comment by ronaldtse** [comment]
@mico I agree with just using "IR". Thanks @mico !
