### ISSUE TITLE
NIST PubID scheme: “Part” representation sometimes goes with “p” or “pt” (always "pt"?)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-nist#87]
* "NIST SP 800-57pt1r4” vs "NIST SP 800-57p3"

We propose to always use `pt` for consistency.

**Comment by ronaldtse** [comment]
The final PubID scheme (#153 ) confirms that `pt` is always used in 2.1.4.

<img width="705" alt="Screenshot 2022-04-07 at 2 07 26 PM" src="https://user-images.githubusercontent.com/11865/162131413-da8e5de7-61de-4eed-a09e-2afcd0712946.png">

<img width="635" alt="Screenshot 2022-04-07 at 2 08 16 PM" src="https://user-images.githubusercontent.com/11865/162131520-048a6df7-bcb1-4430-8003-ce07478ceaeb.png">

@mico is this what we have implement now? If so, please close this, thanks.

**Comment by mico** [comment]
We always render part as "pt".
